version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./logs:/logs
    environment:
      - LOG_LEVEL=INFO
      - LOG_FORMAT='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=CSE312-SobEmoji
    depends_on:
      - db
    command: python app.py

  db:
    image: mongo:latest

    volumes:
      - db_data:/data/db
    # Remove the environment variables that enable authentication
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=your_username
    #   - MONGO_INITDB_ROOT_PASSWORD=your_password
    #   - MONGO_INITDB_DATABASE=ooof

    # Explicitly don't set authentication-related variables
    environment:
      - MONGO_INITDB_DATABASE=CSE312-SobEmoji

volumes:
  db_data: